import { useFeatureSupport } from "@canva/app-hooks";
import {
  Button,
  FormField,
  Rows,
  SegmentedControl,
  Swatch,
  Text,
  TextInput,
} from "@canva/app-ui-kit";
import { openColorSelector } from "@canva/asset";
import { addElementAtCursor, addElementAtPoint } from "@canva/design";
import type {
  BodyPattern,
  CornerEyeDotPattern,
  CornerEyePattern,
  ErrorLevel,
} from "qrdx";
import {
  BODY_PATTERN,
  CORNER_EYE_DOT_PATTERNS,
  CORNER_EYE_PATTERNS,
  getQRAsCanvas,
  getQRData,
  getTemplateIds,
  QRCode,
} from "qrdx";
import { useRef, useState } from "react";
import * as styles from "styles/components.css";

const TEMPLATE_IDS = [
  "default",
  ...getTemplateIds().filter((id) => id !== "default"),
];
const BODY_PATTERNS = [...BODY_PATTERN] as BodyPattern[];
const EYE_PATTERNS: CornerEyePattern[] = [...CORNER_EYE_PATTERNS];
const EYE_DOT_PATTERNS: CornerEyeDotPattern[] = [...CORNER_EYE_DOT_PATTERNS];
const ERROR_LEVELS: ErrorLevel[] = ["L", "M", "Q", "H"];
const PREVIEW_VALUE = "https://qrdx.dev";

interface HorizontalPickerProps<T extends string> {
  label: string;
  options: T[];
  value: T;
  onChange: (v: T) => void;
  renderCard: (option: T) => React.ReactNode;
}

function HorizontalPicker<T extends string>({
  label,
  options,
  value,
  onChange,
  renderCard,
}: HorizontalPickerProps<T>) {
  const scrollRef = useRef<HTMLDivElement>(null);

  const scrollRight = () => {
    if (scrollRef.current) {
      scrollRef.current.scrollBy({ left: 160, behavior: "smooth" });
    }
  };

  return (
    <div>
      <div className={styles.pickerLabel}>
        <Text size="small">{label}</Text>
      </div>
      <div className={styles.pickerRow}>
        <div className={styles.pickerScroll} ref={scrollRef}>
          {options.map((option) => (
            <button
              className={`${styles.pickerCard} ${option === value ? styles.pickerCardSelected : ""}`}
              key={option}
              onClick={() => onChange(option)}
              type="button"
            >
              {renderCard(option)}
            </button>
          ))}
        </div>
        <button
          className={styles.pickerScrollBtn}
          onClick={scrollRight}
          type="button"
        >
          ›
        </button>
      </div>
    </div>
  );
}

export const App = () => {
  const isSupported = useFeatureSupport();
  const addElement = [addElementAtPoint, addElementAtCursor].find((fn) =>
    isSupported(fn)
  );

  const [url, setUrl] = useState("https://qrdx.dev");
  const [fgColor, setFgColor] = useState("#000000");
  const [bgColor, setBgColor] = useState("#ffffff");
  const [eyeColor, setEyeColor] = useState("#000000");
  const [dotColor, setDotColor] = useState("#000000");
  const [bodyPattern, setBodyPattern] = useState<BodyPattern>("circle");
  const [cornerEyePattern, setCornerEyePattern] =
    useState<CornerEyePattern>("gear");
  const [cornerEyeDotPattern, setCornerEyeDotPattern] =
    useState<CornerEyeDotPattern>("circle");
  const [templateId, setTemplateId] = useState("default");
  const [errorLevel, setErrorLevel] = useState<ErrorLevel>("Q");
  const [showLogo, setShowLogo] = useState(false);
  const [logoUrl, setLogoUrl] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);

  const addToDesign = async () => {
    if (!(addElement && url)) return;
    setIsLoading(true);
    setErrorMsg(null);

    try {
      const qrData = getQRData({
        value: url,
        size: 1024,
        fgColor,
        bgColor,
        eyeColor,
        dotColor,
        bodyPattern,
        cornerEyePattern,
        cornerEyeDotPattern,
        level: errorLevel,
        templateId,
        hideLogo: !showLogo,
        logo: logoUrl || undefined,
      });

      const dataUrl = (await getQRAsCanvas(qrData, "image/png")) as string;

      // const thumbData = getQRData({
      //   value: url,
      //   size: 200,
      //   fgColor,
      //   bgColor,
      //   eyeColor,
      //   dotColor,
      //   bodyPattern,
      //   cornerEyePattern,
      //   cornerEyeDotPattern,
      //   level: errorLevel,
      //   templateId,
      //   hideLogo: true,
      // });
      // const thumbnailUrl = (await getQRAsCanvas(
      //   thumbData,
      //   "image/png"
      // )) as string;

      // const asset = await upload({
      //   type: "image",
      //   url: dataUrl,
      //   mimeType: "image/png",
      //   thumbnailUrl,
      //   aiDisclosure: "none",
      //   width: 1024,
      //   height: 1024,
      //   name: `QRdx - ${url.slice(0, 40)}`,
      // });

      // const { ref } = asset;
      // await asset.whenUploaded();

      await addElement({
        type: "image",
        dataUrl,
        altText: { text: "QR code generated by QRdx", decorative: false },
      });
    } catch (err) {
      setErrorMsg(
        err instanceof Error ? err.message : "Failed to add QR code to design"
      );
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className={styles.scrollContainer}>
      <Rows spacing="2u">
        <FormField
          control={(props) => (
            <TextInput
              {...props}
              onChange={setUrl}
              placeholder="https://example.com"
              value={url}
            />
          )}
          label="URL or Text"
        />

        {/* Live Preview */}
        <div className={styles.previewContainer}>
          {url ? (
            <QRCode
              bgColor={bgColor}
              bodyPattern={bodyPattern}
              cornerEyeDotPattern={cornerEyeDotPattern}
              cornerEyePattern={cornerEyePattern}
              dotColor={dotColor}
              eyeColor={eyeColor}
              fgColor={fgColor}
              hideLogo={!showLogo}
              level={errorLevel}
              logo={logoUrl || undefined}
              size={220}
              templateId={templateId}
              value={url}
            />
          ) : (
            <Text size="small" tone="tertiary">
              Enter a URL to preview your QR code
            </Text>
          )}
        </div>

        {/* Templates */}
        <HorizontalPicker
          label="Templates"
          onChange={setTemplateId}
          options={TEMPLATE_IDS}
          renderCard={(id) => (
            <QRCode
              bodyPattern="circle"
              hideLogo
              level="Q"
              size={64}
              templateId={id}
              value={PREVIEW_VALUE}
            />
          )}
          value={templateId}
        />

        {/* Dot Patterns */}
        <HorizontalPicker
          label="Dot Pattern"
          onChange={(v) => setBodyPattern(v as BodyPattern)}
          options={BODY_PATTERNS}
          renderCard={(p) => (
            <QRCode
              bodyPattern={p}
              hideLogo
              level="Q"
              size={64}
              templateId="default"
              value={PREVIEW_VALUE}
            />
          )}
          value={bodyPattern}
        />

        {/* Eye Patterns */}
        <HorizontalPicker
          label="Eye Pattern"
          onChange={(v) => setCornerEyePattern(v as CornerEyePattern)}
          options={EYE_PATTERNS}
          renderCard={(p) => (
            <QRCode
              cornerEyePattern={p}
              hideLogo
              level="Q"
              size={64}
              templateId="default"
              value={PREVIEW_VALUE}
            />
          )}
          value={cornerEyePattern}
        />

        {/* Eye Dot Patterns */}
        <HorizontalPicker
          label="Eye Dot Pattern"
          onChange={(v) => setCornerEyeDotPattern(v as CornerEyeDotPattern)}
          options={EYE_DOT_PATTERNS}
          renderCard={(p) => (
            <QRCode
              cornerEyeDotPattern={p}
              hideLogo
              level="Q"
              size={64}
              templateId="default"
              value={PREVIEW_VALUE}
            />
          )}
          value={cornerEyeDotPattern}
        />

        {/* Colors — Brand Kit aware via openColorSelector */}
        <FormField
          control={(_props) => (
            <div className={styles.colorRow}>
              <Swatch
                fill={[fgColor]}
                onClick={async (e) => {
                  const anchor = (
                    e.currentTarget as HTMLElement
                  ).getBoundingClientRect();
                  await openColorSelector(anchor, {
                    scopes: ["solid"],
                    selectedColor: { type: "solid", hexString: fgColor },
                    onColorSelect: (ev) => {
                      if (ev.selection.type === "solid") {
                        setFgColor(ev.selection.hexString);
                      }
                    },
                  });
                }}
              />
              <Text size="small">{fgColor.toUpperCase()}</Text>
            </div>
          )}
          label="Foreground"
        />

        <FormField
          control={(_props) => (
            <div className={styles.colorRow}>
              <Swatch
                fill={[bgColor]}
                onClick={async (e) => {
                  const anchor = (
                    e.currentTarget as HTMLElement
                  ).getBoundingClientRect();
                  await openColorSelector(anchor, {
                    scopes: ["solid"],
                    selectedColor: { type: "solid", hexString: bgColor },
                    onColorSelect: (ev) => {
                      if (ev.selection.type === "solid") {
                        setBgColor(ev.selection.hexString);
                      }
                    },
                  });
                }}
              />
              <Text size="small">{bgColor.toUpperCase()}</Text>
            </div>
          )}
          label="Background"
        />

        <FormField
          control={(_props) => (
            <div className={styles.colorRow}>
              <Swatch
                fill={[eyeColor]}
                onClick={async (e) => {
                  const anchor = (
                    e.currentTarget as HTMLElement
                  ).getBoundingClientRect();
                  await openColorSelector(anchor, {
                    scopes: ["solid"],
                    selectedColor: { type: "solid", hexString: eyeColor },
                    onColorSelect: (ev) => {
                      if (ev.selection.type === "solid") {
                        setEyeColor(ev.selection.hexString);
                      }
                    },
                  });
                }}
              />
              <Text size="small">{eyeColor.toUpperCase()}</Text>
            </div>
          )}
          label="Eye Color"
        />

        <FormField
          control={(_props) => (
            <div className={styles.colorRow}>
              <Swatch
                fill={[dotColor]}
                onClick={async (e) => {
                  const anchor = (
                    e.currentTarget as HTMLElement
                  ).getBoundingClientRect();
                  await openColorSelector(anchor, {
                    scopes: ["solid"],
                    selectedColor: { type: "solid", hexString: dotColor },
                    onColorSelect: (ev) => {
                      if (ev.selection.type === "solid") {
                        setDotColor(ev.selection.hexString);
                      }
                    },
                  });
                }}
              />
              <Text size="small">{dotColor.toUpperCase()}</Text>
            </div>
          )}
          label="Dot Color"
        />

        {/* Error Correction */}
        <FormField
          control={(props) => (
            <SegmentedControl
              {...props}
              onChange={(v) => setErrorLevel(v as ErrorLevel)}
              options={ERROR_LEVELS.map((l) => ({ label: l, value: l }))}
              value={errorLevel}
            />
          )}
          label="Error Correction"
        />

        {/* Logo */}
        <FormField
          control={(props) => (
            <SegmentedControl
              {...props}
              onChange={(v) => setShowLogo(v === "on")}
              options={[
                { label: "Off", value: "off" },
                { label: "On", value: "on" },
              ]}
              value={showLogo ? "on" : "off"}
            />
          )}
          label="Logo"
        />

        {showLogo && (
          <FormField
            control={(props) => (
              <TextInput
                {...props}
                onChange={setLogoUrl}
                placeholder="https://example.com/logo.png (leave empty for QRdx logo)"
                value={logoUrl}
              />
            )}
            label="Logo URL"
          />
        )}

        {errorMsg && (
          <Text size="small" tone="critical">
            {errorMsg}
          </Text>
        )}

        <Button
          disabled={!(url.trim() && addElement) || isLoading}
          onClick={addToDesign}
          stretch
          variant="primary"
        >
          {isLoading ? "Adding to Design..." : "Add to Design"}
        </Button>
      </Rows>
    </div>
  );
};
