import { useFeatureSupport } from "@canva/app-hooks";
import {
  Button,
  FormField,
  Rows,
  SegmentedControl,
  Select,
  Text,
  TextInput,
  Title,
} from "@canva/app-ui-kit";
import { upload } from "@canva/asset";
import { addElementAtCursor, addElementAtPoint } from "@canva/design";
import type { BodyPattern, ErrorLevel } from "qrdx";
import {
  BODY_PATTERN,
  getQRAsCanvas,
  getQRData,
  getTemplateIds,
  QRCode,
} from "qrdx";
import { useState } from "react";
import * as styles from "styles/components.css";

const TEMPLATE_IDS = [
  "default",
  ...getTemplateIds().filter((id) => id !== "default"),
];
const BODY_PATTERNS = [...BODY_PATTERN] as BodyPattern[];
const ERROR_LEVELS: ErrorLevel[] = ["L", "M", "Q", "H"];

export const App = () => {
  const isSupported = useFeatureSupport();
  const addElement = [addElementAtPoint, addElementAtCursor].find((fn) =>
    isSupported(fn)
  );

  const [url, setUrl] = useState("https://qrdx.dev");
  const [fgColor, setFgColor] = useState("#000000");
  const [bgColor, setBgColor] = useState("#ffffff");
  const [eyeColor, setEyeColor] = useState("#000000");
  const [dotColor, setDotColor] = useState("#000000");
  const [bodyPattern, setBodyPattern] = useState<BodyPattern>("circle");
  const [templateId, setTemplateId] = useState("default");
  const [errorLevel, setErrorLevel] = useState<ErrorLevel>("Q");
  const [showLogo, setShowLogo] = useState(false);
  const [logoUrl, setLogoUrl] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);

  const addToDesign = async () => {
    if (!(addElement && url)) return;
    setIsLoading(true);
    setErrorMsg(null);

    try {
      const qrData = getQRData({
        value: url,
        size: 1024,
        fgColor,
        bgColor,
        eyeColor,
        dotColor,
        bodyPattern,
        level: errorLevel,
        templateId,
        hideLogo: !showLogo,
        logo: logoUrl || undefined,
      });

      const dataUrl = (await getQRAsCanvas(qrData, "image/png")) as string;

      const asset = await upload({
        type: "image",
        url: dataUrl,
        mimeType: "image/png",
        thumbnailUrl: dataUrl,
        aiDisclosure: "none",
        width: 1024,
        height: 1024,
        name: `QRdx - ${url.slice(0, 40)}`,
      });

      const { ref } = asset;
      await asset.whenUploaded();

      await addElement({
        type: "image",
        ref,
        altText: { text: "QR code generated by QRdx", decorative: false },
      });
    } catch (err) {
      setErrorMsg(
        err instanceof Error ? err.message : "Failed to add QR code to design"
      );
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className={styles.scrollContainer}>
      <Rows spacing="2u">
        <Rows spacing="0.5u">
          <Title size="small">QRdx</Title>
          <Text size="small" tone="tertiary">
            Generate custom QR codes and insert them into your design.
          </Text>
        </Rows>

        {/* URL Input */}
        <FormField
          control={(props) => (
            <TextInput
              {...props}
              onChange={setUrl}
              placeholder="https://example.com"
              value={url}
            />
          )}
          label="URL or Text"
        />

        {/* Live Preview — rendered directly as SVG via the QRCode component */}
        <div className={styles.previewContainer}>
          {url ? (
            <QRCode
              bgColor={bgColor}
              bodyPattern={bodyPattern}
              dotColor={dotColor}
              eyeColor={eyeColor}
              fgColor={fgColor}
              hideLogo={!showLogo}
              level={errorLevel}
              logo={logoUrl || undefined}
              size={220}
              templateId={templateId}
              value={url}
            />
          ) : (
            <Text size="small" tone="tertiary">
              Enter a URL to preview your QR code
            </Text>
          )}
        </div>

        {/* Template */}
        <FormField
          control={(props) => (
            <Select
              {...props}
              onChange={setTemplateId}
              options={TEMPLATE_IDS.map((id) => ({ label: id, value: id }))}
              value={templateId}
            />
          )}
          label="Template"
        />

        {/* Dot Pattern */}
        <FormField
          control={(props) => (
            <Select
              {...props}
              onChange={(v) => setBodyPattern(v as BodyPattern)}
              options={BODY_PATTERNS.map((p) => ({ label: p, value: p }))}
              value={bodyPattern}
            />
          )}
          label="Dot Pattern"
        />

        {/* Colors */}
        <FormField
          control={(_props) => (
            <div className={styles.colorRow}>
              <input
                className={styles.colorInput}
                onChange={(e) => setFgColor(e.target.value)}
                title="Foreground color"
                type="color"
                value={fgColor}
              />
              <Text size="small">{fgColor.toUpperCase()}</Text>
            </div>
          )}
          label="Foreground"
        />

        <FormField
          control={(_props) => (
            <div className={styles.colorRow}>
              <input
                className={styles.colorInput}
                onChange={(e) => setBgColor(e.target.value)}
                title="Background color"
                type="color"
                value={bgColor}
              />
              <Text size="small">{bgColor.toUpperCase()}</Text>
            </div>
          )}
          label="Background"
        />

        <FormField
          control={(_props) => (
            <div className={styles.colorRow}>
              <input
                className={styles.colorInput}
                onChange={(e) => setEyeColor(e.target.value)}
                title="Eye color"
                type="color"
                value={eyeColor}
              />
              <Text size="small">{eyeColor.toUpperCase()}</Text>
            </div>
          )}
          label="Eye Color"
        />

        <FormField
          control={(_props) => (
            <div className={styles.colorRow}>
              <input
                className={styles.colorInput}
                onChange={(e) => setDotColor(e.target.value)}
                title="Dot color"
                type="color"
                value={dotColor}
              />
              <Text size="small">{dotColor.toUpperCase()}</Text>
            </div>
          )}
          label="Dot Color"
        />

        {/* Error Correction */}
        <FormField
          control={(props) => (
            <SegmentedControl
              {...props}
              onChange={(v) => setErrorLevel(v as ErrorLevel)}
              options={ERROR_LEVELS.map((l) => ({ label: l, value: l }))}
              value={errorLevel}
            />
          )}
          label="Error Correction"
        />

        {/* Logo */}
        <FormField
          control={(props) => (
            <SegmentedControl
              {...props}
              onChange={(v) => setShowLogo(v === "on")}
              options={[
                { label: "Off", value: "off" },
                { label: "On", value: "on" },
              ]}
              value={showLogo ? "on" : "off"}
            />
          )}
          label="Logo"
        />

        {showLogo && (
          <FormField
            control={(props) => (
              <TextInput
                {...props}
                onChange={setLogoUrl}
                placeholder="https://example.com/logo.png (leave empty for QRdx logo)"
                value={logoUrl}
              />
            )}
            label="Logo URL"
          />
        )}

        {errorMsg && (
          <Text size="small" tone="critical">
            {errorMsg}
          </Text>
        )}

        <Button
          disabled={!(url.trim() && addElement) || isLoading}
          onClick={addToDesign}
          stretch
          variant="primary"
        >
          {isLoading ? "Adding to Design..." : "Add to Design"}
        </Button>
      </Rows>
    </div>
  );
};
