import type { ThemePreset } from "@/types/theme";

/**
 * Built-in QR code presets
 */
export const defaultPresets: Record<string, ThemePreset> = {
  classic: {
    label: "Classic",
    styles: {
      bgColor: "#ffffff",
      fgColor: "#000000",
      eyeColor: "#000000",
      dotColor: "#000000",
      bodyPattern: "circle",
      cornerEyePattern: "gear",
      cornerEyeDotPattern: "circle",
      level: "Q",
    },
  },
  modern: {
    label: "Modern",
    styles: {
      bgColor: "#f8fafc",
      fgColor: "#0f172a",
      eyeColor: "#3b82f6",
      dotColor: "#3b82f6",
      bodyPattern: "rounded",
      cornerEyePattern: "rounded",
      cornerEyeDotPattern: "rounded",
      level: "Q",
    },
  },
  vibrant: {
    label: "Vibrant",
    styles: {
      bgColor: "#fef3c7",
      fgColor: "#7c2d12",
      eyeColor: "#dc2626",
      dotColor: "#ea580c",
      bodyPattern: "diamond",
      cornerEyePattern: "circle",
      cornerEyeDotPattern: "diamond",
      level: "H",
    },
  },
  minimal: {
    label: "Minimal",
    styles: {
      bgColor: "#ffffff",
      fgColor: "#404040",
      eyeColor: "#404040",
      dotColor: "#404040",
      bodyPattern: "square",
      cornerEyePattern: "square",
      cornerEyeDotPattern: "square",
      level: "M",
    },
  },
  gradientBlue: {
    label: "Ocean Blue",
    styles: {
      bgColor: "#eff6ff",
      fgColor: "#1e40af",
      eyeColor: "#3b82f6",
      dotColor: "#60a5fa",
      bodyPattern: "circle-large",
      cornerEyePattern: "gear",
      cornerEyeDotPattern: "circle",
      level: "Q",
    },
  },
  neon: {
    label: "Neon",
    styles: {
      bgColor: "#0f172a",
      fgColor: "#22d3ee",
      eyeColor: "#a855f7",
      dotColor: "#ec4899",
      bodyPattern: "circle-mixed",
      cornerEyePattern: "rounded",
      cornerEyeDotPattern: "rounded",
      level: "Q",
    },
  },
  nature: {
    label: "Nature",
    styles: {
      bgColor: "#f0fdf4",
      fgColor: "#166534",
      eyeColor: "#15803d",
      dotColor: "#16a34a",
      bodyPattern: "rounded",
      cornerEyePattern: "circle",
      cornerEyeDotPattern: "circle",
      level: "Q",
    },
  },
  retro: {
    label: "Retro",
    styles: {
      bgColor: "#fef2f2",
      fgColor: "#7f1d1d",
      eyeColor: "#b91c1c",
      dotColor: "#dc2626",
      bodyPattern: "clean-square",
      cornerEyePattern: "square",
      cornerEyeDotPattern: "square",
      level: "M",
    },
  },
  amberMinimal: {
    label: "Amber Minimal",
    styles: {
      bgColor: "#fffbeb",
      fgColor: "#92400e",
      eyeColor: "#f59e0b",
      dotColor: "#fbbf24",
      bodyPattern: "square",
      cornerEyePattern: "square",
      cornerEyeDotPattern: "square",
      level: "M",
    },
  },
  amethystHaze: {
    label: "Amethyst Haze",
    styles: {
      bgColor: "#faf5ff",
      fgColor: "#6b21a8",
      eyeColor: "#a855f7",
      dotColor: "#c084fc",
      bodyPattern: "rounded",
      cornerEyePattern: "rounded",
      cornerEyeDotPattern: "rounded",
      level: "Q",
    },
  },
  boldTech: {
    label: "Bold Tech",
    styles: {
      bgColor: "#f3e8ff",
      fgColor: "#581c87",
      eyeColor: "#7c3aed",
      dotColor: "#3b82f6",
      bodyPattern: "diamond",
      cornerEyePattern: "gear",
      cornerEyeDotPattern: "diamond",
      level: "H",
    },
  },
  bubblegum: {
    label: "Bubblegum",
    styles: {
      bgColor: "#fdf2f8",
      fgColor: "#9f1239",
      eyeColor: "#ec4899",
      dotColor: "#fbbf24",
      bodyPattern: "circle",
      cornerEyePattern: "circle",
      cornerEyeDotPattern: "circle",
      level: "Q",
    },
  },
  caffeine: {
    label: "Caffeine",
    styles: {
      bgColor: "#fef3c7",
      fgColor: "#78350f",
      eyeColor: "#92400e",
      dotColor: "#a16207",
      bodyPattern: "rounded",
      cornerEyePattern: "rounded",
      cornerEyeDotPattern: "rounded",
      level: "M",
    },
  },
  candyland: {
    label: "Candyland",
    styles: {
      bgColor: "#fef9c3",
      fgColor: "#854d0e",
      eyeColor: "#eab308",
      dotColor: "#3b82f6",
      bodyPattern: "circle",
      cornerEyePattern: "circle",
      cornerEyeDotPattern: "circle",
      level: "Q",
    },
  },
  emerald: {
    label: "Emerald",
    styles: {
      bgColor: "#ecfdf5",
      fgColor: "#064e3b",
      eyeColor: "#10b981",
      dotColor: "#34d399",
      bodyPattern: "rounded",
      cornerEyePattern: "rounded",
      cornerEyeDotPattern: "rounded",
      level: "Q",
    },
  },
  rose: {
    label: "Rose",
    styles: {
      bgColor: "#fff1f2",
      fgColor: "#881337",
      eyeColor: "#e11d48",
      dotColor: "#f43f5e",
      bodyPattern: "circle",
      cornerEyePattern: "circle",
      cornerEyeDotPattern: "circle",
      level: "M",
    },
  },
  slate: {
    label: "Slate",
    styles: {
      bgColor: "#f8fafc",
      fgColor: "#0f172a",
      eyeColor: "#475569",
      dotColor: "#64748b",
      bodyPattern: "square",
      cornerEyePattern: "square",
      cornerEyeDotPattern: "square",
      level: "M",
    },
  },
  sunset: {
    label: "Sunset",
    styles: {
      bgColor: "#fff7ed",
      fgColor: "#9a3412",
      eyeColor: "#ea580c",
      dotColor: "#f97316",
      bodyPattern: "rounded",
      cornerEyePattern: "rounded",
      cornerEyeDotPattern: "rounded",
      level: "Q",
    },
  },
  midnight: {
    label: "Midnight",
    styles: {
      bgColor: "#0f172a",
      fgColor: "#e0e7ff",
      eyeColor: "#6366f1",
      dotColor: "#818cf8",
      bodyPattern: "circle",
      cornerEyePattern: "gear",
      cornerEyeDotPattern: "circle",
      level: "Q",
    },
  },
} as const;
